platform :ios, '16.0'

# Firebase modular headers
pod 'GoogleUtilities', :modular_headers => true
pod 'FirebaseCore', :modular_headers => true
pod 'FirebaseInstallations', :modular_headers => true

require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`) , "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`) , "scripts/react_native_pods")
require 'json'

podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

ENV['RCT_NEW_ARCH_ENABLED'] = podfile_properties['newArchEnabled'] == 'true' ? '1' : '0'
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] = podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']

prepare_react_native_project!

target 'CMPacatuba' do
  use_expo_modules!

  config = use_native_modules!

  # React Native com Fabric habilitado e Hermes
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => true,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Firebase RNFB
  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'
  pod 'RNFBMessaging', :path => '../node_modules/@react-native-firebase/messaging'

  # React Native WebView
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  # Ajustes pós-instalação
  post_install do |installer|
    react_native_post_install(
      installer,
      :mac_catalyst_enabled => false
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Para simulador M1/M2
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
        # Deployment mínimo
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
        # Permite includes não-modulares
        config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      end
    end
  end
end
